[platformio]
src_dir = Src
default_envs = APP_USART_PC

[common]
platform = ststm32
framework = stm32cube
board = genericSTM32F103RC
monitor_speed = 921600
extra_scripts = pre:tools/pio_build_info.py
build_src_flags =
    -Wall
    -Wextra
    -Werror
build_flags =
    -I.
    -ISrc
    -DUSE_HAL_DRIVER
    -DSTM32F103xE
    -DVARIANT_USART
    -lc
    -lm
    -Wl,-z,max-page-size=0x800
    -flto

[env:APP_STLINK]
extra_scripts = ${common.extra_scripts}
board_build.ldscript = STM32F103RCTx_APP.ld
platform = ${common.platform}
framework = ${common.framework}
board = ${common.board}
debug_tool = stlink
upload_protocol = custom
monitor_speed = ${common.monitor_speed}
build_src_flags = ${common.build_src_flags}
build_src_filter = +<*> -<bootloader/>
build_flags = ${common.build_flags}
    -DVECT_TAB_OFFSET=0x00002800U
upload_command = $PYTHONEXE tools/pio_stlink_upload.py --image $SOURCE --address 0x08002800 --max-size 0x3C000 --confirmed-meta-address 0x0803E800

[env:APP_USART_PC]
extra_scripts = ${common.extra_scripts}
board_build.ldscript = STM32F103RCTx_APP.ld
platform = ${common.platform}
framework = ${common.framework}
board = ${common.board}
upload_protocol = custom
upload_port = auto
monitor_speed = ${common.monitor_speed}
build_src_flags = ${common.build_src_flags}
build_src_filter = +<*> -<bootloader/>
build_flags = ${common.build_flags}
    -DVECT_TAB_OFFSET=0x00002800U
upload_command = $PYTHONEXE tools/pio_vesc_upload.py --transport serial --serial-port $UPLOAD_PORT --baud 921600 --boot-baud 921600 --firmware $SOURCE

[env:BOOTLOADER_STLINK]
build_unflags = -flto
extra_scripts = ${common.extra_scripts}
board_build.ldscript = STM32F103RCTx_BOOTLOADER.ld
platform = ${common.platform}
framework = ${common.framework}
board = ${common.board}
debug_tool = stlink
upload_protocol = custom
monitor_speed = ${common.monitor_speed}
build_src_flags = ${common.build_src_flags}
build_src_filter = +<bootloader/>
build_flags = ${common.build_flags}
upload_command = $PYTHONEXE tools/pio_stlink_upload.py --image $SOURCE --address 0x08000000 --max-size 0x2800

[env:APP_STLINK_DIV3]
extends = env:APP_STLINK
build_flags = ${env:APP_STLINK.build_flags}
    -DMCCONF_FOC_CONTROL_DIV=3u

[env:APP_STLINK_DIV2]
extends = env:APP_STLINK
build_flags = ${env:APP_STLINK.build_flags}
    -DMCCONF_FOC_CONTROL_DIV=2u
