// This file is autogenerated by VESC Tool

#include <string.h>
#include "buffer.h"

#include "mcconf_serial.h"

int32_t confgenerator_serialize_mcconf(uint8_t *buffer, const mc_configuration *conf) {
    int32_t ind = 0;
    buffer_append_uint32(buffer, MCCONF_SIGNATURE, &ind);
    buffer[ind++] = conf->pwm_mode;
    buffer[ind++] = conf->comm_mode;
    buffer[ind++] = conf->motor_type;
    buffer[ind++] = conf->sensor_mode;
    buffer_append_float32_auto(buffer, conf->l_current_max, &ind);
    buffer_append_float32_auto(buffer, conf->l_current_min, &ind);
    buffer_append_float32_auto(buffer, conf->l_in_current_max, &ind);
    buffer_append_float32_auto(buffer, conf->l_in_current_min, &ind);
    buffer_append_float32_auto(buffer, conf->l_abs_current_max, &ind);
    buffer_append_float32_auto(buffer, conf->l_min_erpm, &ind);
    buffer_append_float32_auto(buffer, conf->l_max_erpm, &ind);
    buffer_append_float16(buffer, conf->l_erpm_start, 10000, &ind);
    buffer_append_float32_auto(buffer, conf->l_max_erpm_fbrake, &ind);
    buffer_append_float32_auto(buffer, conf->l_max_erpm_fbrake_cc, &ind);
    buffer_append_float32_auto(buffer, conf->l_min_vin, &ind);
    buffer_append_float32_auto(buffer, conf->l_max_vin, &ind);
    buffer_append_float32_auto(buffer, conf->l_battery_cut_start, &ind);
    buffer_append_float32_auto(buffer, conf->l_battery_cut_end, &ind);
    buffer[ind++] = conf->l_slow_abs_current;
    buffer_append_float16(buffer, conf->l_temp_fet_start, 10, &ind);
    buffer_append_float16(buffer, conf->l_temp_fet_end, 10, &ind);
    buffer_append_float16(buffer, conf->l_temp_motor_start, 10, &ind);
    buffer_append_float16(buffer, conf->l_temp_motor_end, 10, &ind);
    buffer_append_float16(buffer, conf->l_temp_accel_dec, 10000, &ind);
    buffer_append_float16(buffer, conf->l_min_duty, 10000, &ind);
    buffer_append_float16(buffer, conf->l_max_duty, 10000, &ind);
    buffer_append_float32_auto(buffer, conf->l_watt_max, &ind);
    buffer_append_float32_auto(buffer, conf->l_watt_min, &ind);
    buffer_append_float16(buffer, conf->l_current_max_scale, 10000, &ind);
    buffer_append_float16(buffer, conf->l_current_min_scale, 10000, &ind);
    buffer_append_float16(buffer, conf->l_duty_start, 10000, &ind);
    buffer_append_float32_auto(buffer, conf->sl_min_erpm, &ind);
    buffer_append_float32_auto(buffer, conf->sl_min_erpm_cycle_int_limit, &ind);
    buffer_append_float32_auto(buffer, conf->sl_max_fullbreak_current_dir_change, &ind);
    buffer_append_float16(buffer, conf->sl_cycle_int_limit, 10, &ind);
    buffer_append_float16(buffer, conf->sl_phase_advance_at_br, 10000, &ind);
    buffer_append_float32_auto(buffer, conf->sl_cycle_int_rpm_br, &ind);
    buffer_append_float32_auto(buffer, conf->sl_bemf_coupling_k, &ind);
    for (int k = 0; k < 8; k++) buffer[ind++] = (uint8_t)conf->hall_table[k];
    buffer_append_float32_auto(buffer, conf->hall_sl_erpm, &ind);
    buffer_append_float32_auto(buffer, conf->foc_current_kp, &ind);
    buffer_append_float32_auto(buffer, conf->foc_current_ki, &ind);
    buffer_append_float32_auto(buffer, conf->foc_f_zv, &ind);
    buffer_append_float32_auto(buffer, conf->foc_dt_us, &ind);
    buffer[ind++] = conf->foc_encoder_inverted;
    buffer_append_float32_auto(buffer, conf->foc_encoder_offset, &ind);
    buffer_append_float32_auto(buffer, conf->foc_encoder_ratio, &ind);
    buffer[ind++] = conf->foc_sensor_mode;
    buffer_append_float32_auto(buffer, conf->foc_pll_kp, &ind);
    buffer_append_float32_auto(buffer, conf->foc_pll_ki, &ind);
    buffer_append_float32_auto(buffer, conf->foc_motor_l, &ind);
    buffer_append_float32_auto(buffer, conf->foc_motor_ld_lq_diff, &ind);
    buffer_append_float32_auto(buffer, conf->foc_motor_r, &ind);
    buffer_append_float32_auto(buffer, conf->foc_motor_flux_linkage, &ind);
    buffer_append_float32_auto(buffer, conf->foc_observer_gain, &ind);
    buffer_append_float32_auto(buffer, conf->foc_observer_gain_slow, &ind);
    buffer_append_float16(buffer, conf->foc_observer_offset, 1000, &ind);
    buffer_append_float32_auto(buffer, conf->foc_duty_dowmramp_kp, &ind);
    buffer_append_float32_auto(buffer, conf->foc_duty_dowmramp_ki, &ind);
    buffer_append_float16(buffer, conf->foc_start_curr_dec, 10000, &ind);
    buffer_append_float32_auto(buffer, conf->foc_start_curr_dec_rpm, &ind);
    buffer_append_float32_auto(buffer, conf->foc_openloop_rpm, &ind);
    buffer_append_float16(buffer, conf->foc_openloop_rpm_low, 1000, &ind);
    /* VESC 6.00 wire-only fields removed in newer datatypes. Keep official 6.00 defaults. */
    buffer_append_float16(buffer, 0.9f, 1000, &ind); /* foc_d_gain_scale_start */
    buffer_append_float16(buffer, 0.2f, 1000, &ind); /* foc_d_gain_scale_max_mod */
    buffer_append_float16(buffer, conf->foc_sl_openloop_hyst, 100, &ind);
    buffer_append_float16(buffer, conf->foc_sl_openloop_time_lock, 100, &ind);
    buffer_append_float16(buffer, conf->foc_sl_openloop_time_ramp, 100, &ind);
    buffer_append_float16(buffer, conf->foc_sl_openloop_time, 100, &ind);
    buffer_append_float16(buffer, conf->foc_sl_openloop_boost_q, 100, &ind);
    buffer_append_float16(buffer, conf->foc_sl_openloop_max_q, 100, &ind);
    for (int k = 0; k < 8; k++) buffer[ind++] = (uint8_t)conf->foc_hall_table[k];
    buffer_append_float32_auto(buffer, conf->foc_hall_interp_erpm, &ind);
    buffer_append_float32_auto(buffer, conf->foc_sl_erpm_start, &ind);
    buffer_append_float32_auto(buffer, conf->foc_sl_erpm, &ind);
    buffer[ind++] = conf->foc_control_sample_mode;
    buffer[ind++] = conf->foc_current_sample_mode;
    buffer[ind++] = conf->foc_sat_comp_mode;
    buffer_append_float16(buffer, conf->foc_sat_comp, 1000, &ind);
    buffer[ind++] = conf->foc_temp_comp;
    buffer_append_float16(buffer, conf->foc_temp_comp_base_temp, 100, &ind);
    buffer_append_float16(buffer, conf->foc_current_filter_const, 10000, &ind);
    buffer[ind++] = conf->foc_cc_decoupling;
    buffer[ind++] = conf->foc_observer_type;
    buffer[ind++] = conf->foc_hfi_amb_mode;
    buffer_append_float16(buffer, conf->foc_hfi_amb_current, 10, &ind);
    buffer[ind++] = (uint8_t)conf->foc_hfi_amb_tres;
    buffer_append_float16(buffer, conf->foc_hfi_voltage_start, 10, &ind);
    buffer_append_float16(buffer, conf->foc_hfi_voltage_run, 10, &ind);
    buffer_append_float16(buffer, conf->foc_hfi_voltage_max, 10, &ind);
    buffer_append_float16(buffer, conf->foc_hfi_gain, 1000, &ind);
    buffer_append_float16(buffer, conf->foc_hfi_max_err, 1000, &ind);
    buffer_append_float16(buffer, conf->foc_hfi_hyst, 100, &ind);
    buffer_append_float32_auto(buffer, conf->foc_sl_erpm_hfi, &ind);
    buffer_append_float32_auto(buffer, conf->foc_hfi_reset_erpm, &ind);
    buffer_append_uint16(buffer, conf->foc_hfi_start_samples, &ind);
    buffer_append_float32_auto(buffer, conf->foc_hfi_obs_ovr_sec, &ind);
    buffer[ind++] = conf->foc_hfi_samples;
    buffer[ind++] = conf->foc_offsets_cal_mode;
    for (int k = 0; k < 3; k++) buffer_append_float32_auto(buffer, conf->foc_offsets_current[k], &ind);
    for (int k = 0; k < 3; k++) buffer_append_float16(buffer, conf->foc_offsets_voltage[k], 10000, &ind);
    for (int k = 0; k < 3; k++) buffer_append_float16(buffer, conf->foc_offsets_voltage_undriven[k], 10000, &ind);
    buffer[ind++] = conf->foc_phase_filter_enable;
    buffer[ind++] = conf->foc_phase_filter_disable_fault;
    buffer_append_float32_auto(buffer, conf->foc_phase_filter_max_erpm, &ind);
    buffer[ind++] = conf->foc_mtpa_mode;
    buffer_append_float32_auto(buffer, conf->foc_fw_current_max, &ind);
    buffer_append_float16(buffer, conf->foc_fw_duty_start, 10000, &ind);
    buffer_append_float16(buffer, conf->foc_fw_ramp_time, 1000, &ind);
    buffer_append_float16(buffer, conf->foc_fw_q_current_factor, 10000, &ind);
    buffer_append_float16(buffer, conf->foc_fw_backoff, 1000, &ind);
    buffer[ind++] = conf->foc_speed_soure;
    buffer[ind++] = conf->foc_short_ls_on_zero_duty;
    buffer_append_float16(buffer, conf->foc_overmod_factor, 10000, &ind);
    buffer_append_float16(buffer, conf->foc_mag_vd_max, 10000, &ind);
    buffer[ind++] = conf->sp_pid_loop_rate;
    buffer_append_float32_auto(buffer, conf->s_pid_kp, &ind);
    buffer_append_float32_auto(buffer, conf->s_pid_ki, &ind);
    buffer_append_float32_auto(buffer, conf->s_pid_kd, &ind);
    buffer_append_float16(buffer, conf->s_pid_kd_filter, 10000, &ind);
    buffer_append_float32_auto(buffer, conf->s_pid_min_erpm, &ind);
    buffer[ind++] = conf->s_pid_allow_braking;
    buffer_append_float32_auto(buffer, conf->s_pid_ramp_erpms_s, &ind);
    buffer[ind++] = conf->s_pid_speed_source;
    buffer_append_float32_auto(buffer, conf->p_pid_kp, &ind);
    buffer_append_float32_auto(buffer, conf->p_pid_ki, &ind);
    buffer_append_float32_auto(buffer, conf->p_pid_kd, &ind);
    buffer_append_float32_auto(buffer, conf->p_pid_kd_proc, &ind);
    buffer_append_float16(buffer, conf->p_pid_kd_filter, 10000, &ind);
    buffer_append_float32_auto(buffer, conf->p_pid_ang_div, &ind);
    buffer_append_float16(buffer, conf->p_pid_gain_dec_angle, 10, &ind);
    buffer_append_float32_auto(buffer, conf->p_pid_offset, &ind);
    buffer_append_float16(buffer, conf->cc_startup_boost_duty, 10000, &ind);
    buffer_append_float32_auto(buffer, conf->cc_min_current, &ind);
    buffer_append_float32_auto(buffer, conf->cc_gain, &ind);
    buffer_append_float16(buffer, conf->cc_ramp_step_max, 10000, &ind);
    buffer_append_int32(buffer, conf->m_fault_stop_time_ms, &ind);
    buffer_append_float16(buffer, conf->m_duty_ramp_step, 10000, &ind);
    buffer_append_float32_auto(buffer, conf->m_current_backoff_gain, &ind);
    buffer_append_uint32(buffer, conf->m_encoder_counts, &ind);
    buffer_append_float16(buffer, conf->m_encoder_sin_amp, 1000, &ind);
    buffer_append_float16(buffer, conf->m_encoder_cos_amp, 1000, &ind);
    buffer_append_float16(buffer, conf->m_encoder_sin_offset, 1000, &ind);
    buffer_append_float16(buffer, conf->m_encoder_cos_offset, 1000, &ind);
    buffer_append_float16(buffer, conf->m_encoder_sincos_filter_constant, 1000, &ind);
    buffer_append_float16(buffer, conf->m_encoder_sincos_phase_correction, 1000, &ind);
    buffer[ind++] = conf->m_sensor_port_mode;
    buffer[ind++] = conf->m_invert_direction;
    buffer[ind++] = conf->m_drv8301_oc_mode;
    buffer[ind++] = (uint8_t)conf->m_drv8301_oc_adj;
    buffer_append_float32_auto(buffer, conf->m_bldc_f_sw_min, &ind);
    buffer_append_float32_auto(buffer, conf->m_bldc_f_sw_max, &ind);
    buffer_append_float32_auto(buffer, conf->m_dc_f_sw, &ind);
    buffer_append_float32_auto(buffer, conf->m_ntc_motor_beta, &ind);
    buffer[ind++] = conf->m_out_aux_mode;
    buffer[ind++] = conf->m_motor_temp_sens_type;
    buffer_append_float32_auto(buffer, conf->m_ptc_motor_coeff, &ind);
    buffer_append_float16(buffer, conf->m_ntcx_ptcx_res, 0.1f, &ind);
    buffer_append_float16(buffer, conf->m_ntcx_ptcx_temp_base, 10, &ind);
    buffer[ind++] = (uint8_t)conf->m_hall_extra_samples;
    buffer[ind++] = (uint8_t)conf->m_batt_filter_const;
    buffer[ind++] = (uint8_t)conf->si_motor_poles;
    buffer_append_float32_auto(buffer, conf->si_gear_ratio, &ind);
    buffer_append_float32_auto(buffer, conf->si_wheel_diameter, &ind);
    buffer[ind++] = conf->si_battery_type;
    buffer[ind++] = (uint8_t)conf->si_battery_cells;
    buffer_append_float32_auto(buffer, conf->si_battery_ah, &ind);
    buffer_append_float32_auto(buffer, conf->si_motor_nl_current, &ind);
    buffer[ind++] = conf->bms.type;
    buffer[ind++] = conf->bms.limit_mode;
    buffer_append_float16(buffer, conf->bms.t_limit_start, 100, &ind);
    buffer_append_float16(buffer, conf->bms.t_limit_end, 100, &ind);
    buffer_append_float16(buffer, conf->bms.soc_limit_start, 1000, &ind);
    buffer_append_float16(buffer, conf->bms.soc_limit_end, 1000, &ind);
    buffer[ind++] = conf->bms.fwd_can_mode;
    return ind;
}

/* VESC 6.00 had app_balance_conf in the App Configuration wire format.
 * Modern datatypes.h no longer exposes that sub-structure, but VESC Tool 6.x
 * still expects these bytes at this exact location. This board does not run
 * the balance application, so serialize deterministic zero/default values and
 * consume/discard them on write. This preserves the exact 6.00 wire layout
 * without forking the official datatypes.h. */
static void appconf6_append_balance_placeholder(uint8_t *buffer, int32_t *ind) {
    buffer[(*ind)++] = 0u; /* pid_mode */
    for (uint8_t n = 0u; n < 6u; ++n) buffer_append_float32_auto(buffer, 0.0f, ind); /* kp..kd2 */
    buffer_append_uint16(buffer, 0u, ind); /* hertz */
    buffer_append_uint16(buffer, 0u, ind); /* loop_time_filter */
    for (uint8_t n = 0u; n < 5u; ++n) buffer_append_float32_auto(buffer, 0.0f, ind); /* fault values */
    for (uint8_t n = 0u; n < 6u; ++n) buffer_append_uint16(buffer, 0u, ind); /* fault delays */
    buffer[(*ind)++] = 0u; /* fault_is_dual_switch */
    buffer_append_float16(buffer, 0.0f, 100, ind);  /* tiltback_duty_angle */
    buffer_append_float16(buffer, 0.0f, 100, ind);  /* tiltback_duty_speed */
    buffer_append_float16(buffer, 0.0f, 1000, ind); /* tiltback_duty */
    buffer_append_float16(buffer, 0.0f, 100, ind);  /* tiltback_hv_angle */
    buffer_append_float16(buffer, 0.0f, 100, ind);  /* tiltback_hv_speed */
    buffer_append_float32_auto(buffer, 0.0f, ind);  /* tiltback_hv */
    buffer_append_float16(buffer, 0.0f, 100, ind);  /* tiltback_lv_angle */
    buffer_append_float16(buffer, 0.0f, 100, ind);  /* tiltback_lv_speed */
    buffer_append_float32_auto(buffer, 0.0f, ind);  /* tiltback_lv */
    buffer_append_float16(buffer, 0.0f, 100, ind);  /* tiltback_return_speed */
    buffer_append_float32_auto(buffer, 0.0f, ind);  /* tiltback_constant */
    buffer_append_uint16(buffer, 0u, ind);           /* tiltback_constant_erpm */
    buffer_append_float32_auto(buffer, 0.0f, ind);  /* tiltback_variable */
    buffer_append_float32_auto(buffer, 0.0f, ind);  /* tiltback_variable_max */
    buffer_append_float16(buffer, 0.0f, 100, ind);  /* noseangling_speed */
    for (uint8_t n = 0u; n < 4u; ++n) buffer_append_float32_auto(buffer, 0.0f, ind); /* startup/deadzone */
    buffer[(*ind)++] = 0u; /* multi_esc */
    for (uint8_t n = 0u; n < 6u; ++n) buffer_append_float32_auto(buffer, 0.0f, ind); /* yaw/roll/brake */
    buffer_append_uint16(buffer, 0u, ind); /* brake_timeout */
    buffer_append_float32_auto(buffer, 0.0f, ind); /* yaw_current_clamp */
    buffer_append_float32_auto(buffer, 0.0f, ind); /* ki_limit */
    buffer_append_uint16(buffer, 0u, ind); /* kd LPF */
    buffer_append_uint16(buffer, 0u, ind); /* kd HPF */
    for (uint8_t n = 0u; n < 12u; ++n) buffer_append_float32_auto(buffer, 0.0f, ind); /* booster..turntilt_start_angle */
    buffer_append_uint16(buffer, 0u, ind); /* turntilt_start_erpm */
    buffer_append_float32_auto(buffer, 0.0f, ind); /* turntilt_speed */
    buffer_append_uint16(buffer, 0u, ind); /* turntilt_erpm_boost */
    buffer_append_uint16(buffer, 0u, ind); /* turntilt_erpm_boost_end */
}

static void appconf6_skip_balance_placeholder(const uint8_t *buffer, int32_t *ind) {
    (void)buffer[(*ind)++];
    for (uint8_t n = 0u; n < 6u; ++n) (void)buffer_get_float32_auto(buffer, ind);
    (void)buffer_get_uint16(buffer, ind); (void)buffer_get_uint16(buffer, ind);
    for (uint8_t n = 0u; n < 5u; ++n) (void)buffer_get_float32_auto(buffer, ind);
    for (uint8_t n = 0u; n < 6u; ++n) (void)buffer_get_uint16(buffer, ind);
    (void)buffer[(*ind)++];
    (void)buffer_get_float16(buffer, 100, ind); (void)buffer_get_float16(buffer, 100, ind);
    (void)buffer_get_float16(buffer, 1000, ind); (void)buffer_get_float16(buffer, 100, ind);
    (void)buffer_get_float16(buffer, 100, ind); (void)buffer_get_float32_auto(buffer, ind);
    (void)buffer_get_float16(buffer, 100, ind); (void)buffer_get_float16(buffer, 100, ind);
    (void)buffer_get_float32_auto(buffer, ind); (void)buffer_get_float16(buffer, 100, ind);
    (void)buffer_get_float32_auto(buffer, ind); (void)buffer_get_uint16(buffer, ind);
    (void)buffer_get_float32_auto(buffer, ind); (void)buffer_get_float32_auto(buffer, ind);
    (void)buffer_get_float16(buffer, 100, ind);
    for (uint8_t n = 0u; n < 4u; ++n) (void)buffer_get_float32_auto(buffer, ind);
    (void)buffer[(*ind)++];
    for (uint8_t n = 0u; n < 6u; ++n) (void)buffer_get_float32_auto(buffer, ind);
    (void)buffer_get_uint16(buffer, ind);
    (void)buffer_get_float32_auto(buffer, ind); (void)buffer_get_float32_auto(buffer, ind);
    (void)buffer_get_uint16(buffer, ind); (void)buffer_get_uint16(buffer, ind);
    for (uint8_t n = 0u; n < 12u; ++n) (void)buffer_get_float32_auto(buffer, ind);
    (void)buffer_get_uint16(buffer, ind); (void)buffer_get_float32_auto(buffer, ind);
    (void)buffer_get_uint16(buffer, ind); (void)buffer_get_uint16(buffer, ind);
}

int32_t confgenerator_serialize_appconf(uint8_t *buffer, const app_configuration *conf) {
	int32_t ind = 0;

	buffer_append_uint32(buffer, APPCONF_SIGNATURE, &ind);

	buffer[ind++] = (uint8_t)conf->controller_id;
	buffer_append_uint32(buffer, conf->timeout_msec, &ind);
	buffer_append_float32_auto(buffer, conf->timeout_brake_current, &ind);
	buffer_append_uint16(buffer, conf->can_status_rate_1, &ind);
	buffer_append_uint16(buffer, conf->can_status_rate_2, &ind);
	buffer[ind++] = conf->can_status_msgs_r1;
	buffer[ind++] = conf->can_status_msgs_r2;
	buffer[ind++] = conf->can_baud_rate;
	buffer[ind++] = conf->pairing_done;
	buffer[ind++] = conf->permanent_uart_enabled;
	buffer[ind++] = conf->shutdown_mode;
	buffer[ind++] = conf->can_mode;
	buffer[ind++] = (uint8_t)conf->uavcan_esc_index;
	buffer[ind++] = conf->uavcan_raw_mode;
	buffer_append_float32_auto(buffer, conf->uavcan_raw_rpm_max, &ind);
	buffer[ind++] = conf->uavcan_status_current_mode;
	buffer[ind++] = conf->servo_out_enable;
	buffer[ind++] = conf->kill_sw_mode;
	buffer[ind++] = conf->app_to_use;
	buffer[ind++] = conf->app_ppm_conf.ctrl_type;
	buffer_append_float32_auto(buffer, conf->app_ppm_conf.pid_max_erpm, &ind);
	buffer_append_float32_auto(buffer, conf->app_ppm_conf.hyst, &ind);
	buffer_append_float32_auto(buffer, conf->app_ppm_conf.pulse_start, &ind);
	buffer_append_float32_auto(buffer, conf->app_ppm_conf.pulse_end, &ind);
	buffer_append_float32_auto(buffer, conf->app_ppm_conf.pulse_center, &ind);
	buffer[ind++] = conf->app_ppm_conf.median_filter;
	buffer[ind++] = conf->app_ppm_conf.safe_start;
	buffer_append_float32_auto(buffer, conf->app_ppm_conf.throttle_exp, &ind);
	buffer_append_float32_auto(buffer, conf->app_ppm_conf.throttle_exp_brake, &ind);
	buffer[ind++] = conf->app_ppm_conf.throttle_exp_mode;
	buffer_append_float32_auto(buffer, conf->app_ppm_conf.ramp_time_pos, &ind);
	buffer_append_float32_auto(buffer, conf->app_ppm_conf.ramp_time_neg, &ind);
	buffer[ind++] = conf->app_ppm_conf.multi_esc;
	buffer[ind++] = conf->app_ppm_conf.tc;
	buffer_append_float32_auto(buffer, conf->app_ppm_conf.tc_max_diff, &ind);
	buffer_append_float16(buffer, conf->app_ppm_conf.max_erpm_for_dir, 1, &ind);
	buffer_append_float32_auto(buffer, conf->app_ppm_conf.smart_rev_max_duty, &ind);
	buffer_append_float32_auto(buffer, conf->app_ppm_conf.smart_rev_ramp_time, &ind);
	buffer[ind++] = conf->app_adc_conf.ctrl_type;
	buffer_append_float32_auto(buffer, conf->app_adc_conf.hyst, &ind);
	buffer_append_float16(buffer, conf->app_adc_conf.voltage_start, 1000, &ind);
	buffer_append_float16(buffer, conf->app_adc_conf.voltage_end, 1000, &ind);
	buffer_append_float16(buffer, conf->app_adc_conf.voltage_min, 1000, &ind);
	buffer_append_float16(buffer, conf->app_adc_conf.voltage_max, 1000, &ind);
	buffer_append_float16(buffer, conf->app_adc_conf.voltage_center, 1000, &ind);
	buffer_append_float16(buffer, conf->app_adc_conf.voltage2_start, 1000, &ind);
	buffer_append_float16(buffer, conf->app_adc_conf.voltage2_end, 1000, &ind);
	buffer[ind++] = conf->app_adc_conf.use_filter;
	buffer[ind++] = conf->app_adc_conf.safe_start;
	buffer[ind++] = conf->app_adc_conf.buttons;
	buffer[ind++] = conf->app_adc_conf.voltage_inverted;
	buffer[ind++] = conf->app_adc_conf.voltage2_inverted;
	buffer_append_float32_auto(buffer, conf->app_adc_conf.throttle_exp, &ind);
	buffer_append_float32_auto(buffer, conf->app_adc_conf.throttle_exp_brake, &ind);
	buffer[ind++] = conf->app_adc_conf.throttle_exp_mode;
	buffer_append_float32_auto(buffer, conf->app_adc_conf.ramp_time_pos, &ind);
	buffer_append_float32_auto(buffer, conf->app_adc_conf.ramp_time_neg, &ind);
	buffer[ind++] = conf->app_adc_conf.multi_esc;
	buffer[ind++] = conf->app_adc_conf.tc;
	buffer_append_float32_auto(buffer, conf->app_adc_conf.tc_max_diff, &ind);
	buffer_append_uint16(buffer, conf->app_adc_conf.update_rate_hz, &ind);
	buffer_append_uint32(buffer, conf->app_uart_baudrate, &ind);
	buffer[ind++] = conf->app_chuk_conf.ctrl_type;
	buffer_append_float32_auto(buffer, conf->app_chuk_conf.hyst, &ind);
	buffer_append_float32_auto(buffer, conf->app_chuk_conf.ramp_time_pos, &ind);
	buffer_append_float32_auto(buffer, conf->app_chuk_conf.ramp_time_neg, &ind);
	buffer_append_float32_auto(buffer, conf->app_chuk_conf.stick_erpm_per_s_in_cc, &ind);
	buffer_append_float32_auto(buffer, conf->app_chuk_conf.throttle_exp, &ind);
	buffer_append_float32_auto(buffer, conf->app_chuk_conf.throttle_exp_brake, &ind);
	buffer[ind++] = conf->app_chuk_conf.throttle_exp_mode;
	buffer[ind++] = conf->app_chuk_conf.multi_esc;
	buffer[ind++] = conf->app_chuk_conf.tc;
	buffer_append_float32_auto(buffer, conf->app_chuk_conf.tc_max_diff, &ind);
	buffer[ind++] = conf->app_chuk_conf.use_smart_rev;
	buffer_append_float32_auto(buffer, conf->app_chuk_conf.smart_rev_max_duty, &ind);
	buffer_append_float32_auto(buffer, conf->app_chuk_conf.smart_rev_ramp_time, &ind);
	buffer[ind++] = conf->app_nrf_conf.speed;
	buffer[ind++] = conf->app_nrf_conf.power;
	buffer[ind++] = conf->app_nrf_conf.crc_type;
	buffer[ind++] = conf->app_nrf_conf.retry_delay;
	buffer[ind++] = (uint8_t)conf->app_nrf_conf.retries;
	buffer[ind++] = (uint8_t)conf->app_nrf_conf.channel;
	buffer[ind++] = (uint8_t)conf->app_nrf_conf.address[0];
	buffer[ind++] = (uint8_t)conf->app_nrf_conf.address[1];
	buffer[ind++] = (uint8_t)conf->app_nrf_conf.address[2];
	buffer[ind++] = conf->app_nrf_conf.send_crc_ack;
	appconf6_append_balance_placeholder(buffer, &ind);
	buffer[ind++] = conf->app_pas_conf.ctrl_type;
	buffer[ind++] = conf->app_pas_conf.sensor_type;
	buffer_append_float16(buffer, conf->app_pas_conf.current_scaling, 1000, &ind);
	buffer_append_float16(buffer, conf->app_pas_conf.pedal_rpm_start, 10, &ind);
	buffer_append_float16(buffer, conf->app_pas_conf.pedal_rpm_end, 10, &ind);
	buffer[ind++] = conf->app_pas_conf.invert_pedal_direction;
	buffer_append_uint16(buffer, conf->app_pas_conf.magnets, &ind);
	buffer[ind++] = conf->app_pas_conf.use_filter;
	buffer_append_float16(buffer, conf->app_pas_conf.ramp_time_pos, 100, &ind);
	buffer_append_float16(buffer, conf->app_pas_conf.ramp_time_neg, 100, &ind);
	buffer_append_uint16(buffer, conf->app_pas_conf.update_rate_hz, &ind);
	buffer[ind++] = conf->imu_conf.type;
	buffer[ind++] = conf->imu_conf.mode;
	buffer[ind++] = conf->imu_conf.filter;
	buffer_append_float16(buffer, conf->imu_conf.accel_lowpass_filter_x, 1, &ind);
	buffer_append_float16(buffer, conf->imu_conf.accel_lowpass_filter_y, 1, &ind);
	buffer_append_float16(buffer, conf->imu_conf.accel_lowpass_filter_z, 1, &ind);
	buffer_append_float16(buffer, conf->imu_conf.gyro_lowpass_filter, 1, &ind);
	buffer_append_uint16(buffer, conf->imu_conf.sample_rate_hz, &ind);
	buffer[ind++] = conf->imu_conf.use_magnetometer;
	buffer_append_float32_auto(buffer, conf->imu_conf.accel_confidence_decay, &ind);
	buffer_append_float32_auto(buffer, conf->imu_conf.mahony_kp, &ind);
	buffer_append_float32_auto(buffer, conf->imu_conf.mahony_ki, &ind);
	buffer_append_float32_auto(buffer, conf->imu_conf.madgwick_beta, &ind);
	buffer_append_float32_auto(buffer, conf->imu_conf.rot_roll, &ind);
	buffer_append_float32_auto(buffer, conf->imu_conf.rot_pitch, &ind);
	buffer_append_float32_auto(buffer, conf->imu_conf.rot_yaw, &ind);
	buffer_append_float32_auto(buffer, conf->imu_conf.accel_offsets[0], &ind);
	buffer_append_float32_auto(buffer, conf->imu_conf.accel_offsets[1], &ind);
	buffer_append_float32_auto(buffer, conf->imu_conf.accel_offsets[2], &ind);
	buffer_append_float32_auto(buffer, conf->imu_conf.gyro_offsets[0], &ind);
	buffer_append_float32_auto(buffer, conf->imu_conf.gyro_offsets[1], &ind);
	buffer_append_float32_auto(buffer, conf->imu_conf.gyro_offsets[2], &ind);

	return ind;
}

bool confgenerator_deserialize_mcconf(const uint8_t *buffer, mc_configuration *conf) {
    int32_t ind = 0;
    if (buffer_get_uint32(buffer, &ind) != MCCONF_SIGNATURE) return false;
    conf->pwm_mode = buffer[ind++];
    conf->comm_mode = buffer[ind++];
    conf->motor_type = buffer[ind++];
    conf->sensor_mode = buffer[ind++];
    conf->l_current_max = buffer_get_float32_auto(buffer, &ind);
    conf->l_current_min = buffer_get_float32_auto(buffer, &ind);
    conf->l_in_current_max = buffer_get_float32_auto(buffer, &ind);
    conf->l_in_current_min = buffer_get_float32_auto(buffer, &ind);
    conf->l_abs_current_max = buffer_get_float32_auto(buffer, &ind);
    conf->l_min_erpm = buffer_get_float32_auto(buffer, &ind);
    conf->l_max_erpm = buffer_get_float32_auto(buffer, &ind);
    conf->l_erpm_start = buffer_get_float16(buffer, 10000, &ind);
    conf->l_max_erpm_fbrake = buffer_get_float32_auto(buffer, &ind);
    conf->l_max_erpm_fbrake_cc = buffer_get_float32_auto(buffer, &ind);
    conf->l_min_vin = buffer_get_float32_auto(buffer, &ind);
    conf->l_max_vin = buffer_get_float32_auto(buffer, &ind);
    conf->l_battery_cut_start = buffer_get_float32_auto(buffer, &ind);
    conf->l_battery_cut_end = buffer_get_float32_auto(buffer, &ind);
    conf->l_slow_abs_current = buffer[ind++];
    conf->l_temp_fet_start = buffer_get_float16(buffer, 10, &ind);
    conf->l_temp_fet_end = buffer_get_float16(buffer, 10, &ind);
    conf->l_temp_motor_start = buffer_get_float16(buffer, 10, &ind);
    conf->l_temp_motor_end = buffer_get_float16(buffer, 10, &ind);
    conf->l_temp_accel_dec = buffer_get_float16(buffer, 10000, &ind);
    conf->l_min_duty = buffer_get_float16(buffer, 10000, &ind);
    conf->l_max_duty = buffer_get_float16(buffer, 10000, &ind);
    conf->l_watt_max = buffer_get_float32_auto(buffer, &ind);
    conf->l_watt_min = buffer_get_float32_auto(buffer, &ind);
    conf->l_current_max_scale = buffer_get_float16(buffer, 10000, &ind);
    conf->l_current_min_scale = buffer_get_float16(buffer, 10000, &ind);
    conf->l_duty_start = buffer_get_float16(buffer, 10000, &ind);
    conf->sl_min_erpm = buffer_get_float32_auto(buffer, &ind);
    conf->sl_min_erpm_cycle_int_limit = buffer_get_float32_auto(buffer, &ind);
    conf->sl_max_fullbreak_current_dir_change = buffer_get_float32_auto(buffer, &ind);
    conf->sl_cycle_int_limit = buffer_get_float16(buffer, 10, &ind);
    conf->sl_phase_advance_at_br = buffer_get_float16(buffer, 10000, &ind);
    conf->sl_cycle_int_rpm_br = buffer_get_float32_auto(buffer, &ind);
    conf->sl_bemf_coupling_k = buffer_get_float32_auto(buffer, &ind);
    for (int k = 0; k < 8; k++) conf->hall_table[k] = (int8_t)buffer[ind++];
    conf->hall_sl_erpm = buffer_get_float32_auto(buffer, &ind);
    conf->foc_current_kp = buffer_get_float32_auto(buffer, &ind);
    conf->foc_current_ki = buffer_get_float32_auto(buffer, &ind);
    conf->foc_f_zv = buffer_get_float32_auto(buffer, &ind);
    conf->foc_dt_us = buffer_get_float32_auto(buffer, &ind);
    conf->foc_encoder_inverted = buffer[ind++];
    conf->foc_encoder_offset = buffer_get_float32_auto(buffer, &ind);
    conf->foc_encoder_ratio = buffer_get_float32_auto(buffer, &ind);
    conf->foc_sensor_mode = buffer[ind++];
    conf->foc_pll_kp = buffer_get_float32_auto(buffer, &ind);
    conf->foc_pll_ki = buffer_get_float32_auto(buffer, &ind);
    conf->foc_motor_l = buffer_get_float32_auto(buffer, &ind);
    conf->foc_motor_ld_lq_diff = buffer_get_float32_auto(buffer, &ind);
    conf->foc_motor_r = buffer_get_float32_auto(buffer, &ind);
    conf->foc_motor_flux_linkage = buffer_get_float32_auto(buffer, &ind);
    conf->foc_observer_gain = buffer_get_float32_auto(buffer, &ind);
    conf->foc_observer_gain_slow = buffer_get_float32_auto(buffer, &ind);
    conf->foc_observer_offset = buffer_get_float16(buffer, 1000, &ind);
    conf->foc_duty_dowmramp_kp = buffer_get_float32_auto(buffer, &ind);
    conf->foc_duty_dowmramp_ki = buffer_get_float32_auto(buffer, &ind);
    conf->foc_start_curr_dec = buffer_get_float16(buffer, 10000, &ind);
    conf->foc_start_curr_dec_rpm = buffer_get_float32_auto(buffer, &ind);
    conf->foc_openloop_rpm = buffer_get_float32_auto(buffer, &ind);
    conf->foc_openloop_rpm_low = buffer_get_float16(buffer, 1000, &ind);
    (void)buffer_get_float16(buffer, 1000, &ind); /* foc_d_gain_scale_start */
    (void)buffer_get_float16(buffer, 1000, &ind); /* foc_d_gain_scale_max_mod */
    conf->foc_sl_openloop_hyst = buffer_get_float16(buffer, 100, &ind);
    conf->foc_sl_openloop_time_lock = buffer_get_float16(buffer, 100, &ind);
    conf->foc_sl_openloop_time_ramp = buffer_get_float16(buffer, 100, &ind);
    conf->foc_sl_openloop_time = buffer_get_float16(buffer, 100, &ind);
    conf->foc_sl_openloop_boost_q = buffer_get_float16(buffer, 100, &ind);
    conf->foc_sl_openloop_max_q = buffer_get_float16(buffer, 100, &ind);
    for (int k = 0; k < 8; k++) conf->foc_hall_table[k] = (int8_t)buffer[ind++];
    conf->foc_hall_interp_erpm = buffer_get_float32_auto(buffer, &ind);
    conf->foc_sl_erpm_start = buffer_get_float32_auto(buffer, &ind);
    conf->foc_sl_erpm = buffer_get_float32_auto(buffer, &ind);
    conf->foc_control_sample_mode = (mc_foc_control_sample_mode)buffer[ind++];
    conf->foc_current_sample_mode = (mc_foc_current_sample_mode)buffer[ind++];
    conf->foc_sat_comp_mode = buffer[ind++];
    conf->foc_sat_comp = buffer_get_float16(buffer, 1000, &ind);
    conf->foc_temp_comp = buffer[ind++];
    conf->foc_temp_comp_base_temp = buffer_get_float16(buffer, 100, &ind);
    conf->foc_current_filter_const = buffer_get_float16(buffer, 10000, &ind);
    conf->foc_cc_decoupling = buffer[ind++];
    conf->foc_observer_type = buffer[ind++];
    conf->foc_hfi_amb_mode = buffer[ind++];
    conf->foc_hfi_amb_current = buffer_get_float16(buffer, 10, &ind);
    conf->foc_hfi_amb_tres = buffer[ind++];
    conf->foc_hfi_voltage_start = buffer_get_float16(buffer, 10, &ind);
    conf->foc_hfi_voltage_run = buffer_get_float16(buffer, 10, &ind);
    conf->foc_hfi_voltage_max = buffer_get_float16(buffer, 10, &ind);
    conf->foc_hfi_gain = buffer_get_float16(buffer, 1000, &ind);
    conf->foc_hfi_max_err = buffer_get_float16(buffer, 1000, &ind);
    conf->foc_hfi_hyst = buffer_get_float16(buffer, 100, &ind);
    conf->foc_sl_erpm_hfi = buffer_get_float32_auto(buffer, &ind);
    conf->foc_hfi_reset_erpm = buffer_get_float32_auto(buffer, &ind);
    conf->foc_hfi_start_samples = buffer_get_uint16(buffer, &ind);
    conf->foc_hfi_obs_ovr_sec = buffer_get_float32_auto(buffer, &ind);
    conf->foc_hfi_samples = buffer[ind++];
    conf->foc_offsets_cal_mode = buffer[ind++];
    for (int k = 0; k < 3; k++) conf->foc_offsets_current[k] = buffer_get_float32_auto(buffer, &ind);
    for (int k = 0; k < 3; k++) conf->foc_offsets_voltage[k] = buffer_get_float16(buffer, 10000, &ind);
    for (int k = 0; k < 3; k++) conf->foc_offsets_voltage_undriven[k] = buffer_get_float16(buffer, 10000, &ind);
    conf->foc_phase_filter_enable = buffer[ind++];
    conf->foc_phase_filter_disable_fault = buffer[ind++];
    conf->foc_phase_filter_max_erpm = buffer_get_float32_auto(buffer, &ind);
    conf->foc_mtpa_mode = buffer[ind++];
    conf->foc_fw_current_max = buffer_get_float32_auto(buffer, &ind);
    conf->foc_fw_duty_start = buffer_get_float16(buffer, 10000, &ind);
    conf->foc_fw_ramp_time = buffer_get_float16(buffer, 1000, &ind);
    conf->foc_fw_q_current_factor = buffer_get_float16(buffer, 10000, &ind);
    conf->foc_fw_backoff = buffer_get_float16(buffer, 1000, &ind);
    conf->foc_speed_soure = buffer[ind++];
    conf->foc_short_ls_on_zero_duty = buffer[ind++];
    conf->foc_overmod_factor = buffer_get_float16(buffer, 10000, &ind);
    conf->foc_mag_vd_max = buffer_get_float16(buffer, 10000, &ind);
    conf->sp_pid_loop_rate = buffer[ind++];
    conf->s_pid_kp = buffer_get_float32_auto(buffer, &ind);
    conf->s_pid_ki = buffer_get_float32_auto(buffer, &ind);
    conf->s_pid_kd = buffer_get_float32_auto(buffer, &ind);
    conf->s_pid_kd_filter = buffer_get_float16(buffer, 10000, &ind);
    conf->s_pid_min_erpm = buffer_get_float32_auto(buffer, &ind);
    conf->s_pid_allow_braking = buffer[ind++];
    conf->s_pid_ramp_erpms_s = buffer_get_float32_auto(buffer, &ind);
    conf->s_pid_speed_source = buffer[ind++];
    conf->p_pid_kp = buffer_get_float32_auto(buffer, &ind);
    conf->p_pid_ki = buffer_get_float32_auto(buffer, &ind);
    conf->p_pid_kd = buffer_get_float32_auto(buffer, &ind);
    conf->p_pid_kd_proc = buffer_get_float32_auto(buffer, &ind);
    conf->p_pid_kd_filter = buffer_get_float16(buffer, 10000, &ind);
    conf->p_pid_ang_div = buffer_get_float32_auto(buffer, &ind);
    conf->p_pid_gain_dec_angle = buffer_get_float16(buffer, 10, &ind);
    conf->p_pid_offset = buffer_get_float32_auto(buffer, &ind);
    conf->cc_startup_boost_duty = buffer_get_float16(buffer, 10000, &ind);
    conf->cc_min_current = buffer_get_float32_auto(buffer, &ind);
    conf->cc_gain = buffer_get_float32_auto(buffer, &ind);
    conf->cc_ramp_step_max = buffer_get_float16(buffer, 10000, &ind);
    conf->m_fault_stop_time_ms = buffer_get_int32(buffer, &ind);
    conf->m_duty_ramp_step = buffer_get_float16(buffer, 10000, &ind);
    conf->m_current_backoff_gain = buffer_get_float32_auto(buffer, &ind);
    conf->m_encoder_counts = buffer_get_uint32(buffer, &ind);
    conf->m_encoder_sin_amp = buffer_get_float16(buffer, 1000, &ind);
    conf->m_encoder_cos_amp = buffer_get_float16(buffer, 1000, &ind);
    conf->m_encoder_sin_offset = buffer_get_float16(buffer, 1000, &ind);
    conf->m_encoder_cos_offset = buffer_get_float16(buffer, 1000, &ind);
    conf->m_encoder_sincos_filter_constant = buffer_get_float16(buffer, 1000, &ind);
    conf->m_encoder_sincos_phase_correction = buffer_get_float16(buffer, 1000, &ind);
    conf->m_sensor_port_mode = buffer[ind++];
    conf->m_invert_direction = buffer[ind++];
    conf->m_drv8301_oc_mode = buffer[ind++];
    conf->m_drv8301_oc_adj = buffer[ind++];
    conf->m_bldc_f_sw_min = buffer_get_float32_auto(buffer, &ind);
    conf->m_bldc_f_sw_max = buffer_get_float32_auto(buffer, &ind);
    conf->m_dc_f_sw = buffer_get_float32_auto(buffer, &ind);
    conf->m_ntc_motor_beta = buffer_get_float32_auto(buffer, &ind);
    conf->m_out_aux_mode = buffer[ind++];
    conf->m_motor_temp_sens_type = buffer[ind++];
    conf->m_ptc_motor_coeff = buffer_get_float32_auto(buffer, &ind);
    conf->m_ntcx_ptcx_res = buffer_get_float16(buffer, 0.1f, &ind);
    conf->m_ntcx_ptcx_temp_base = buffer_get_float16(buffer, 10, &ind);
    conf->m_hall_extra_samples = buffer[ind++];
    conf->m_batt_filter_const = buffer[ind++];
    conf->si_motor_poles = buffer[ind++];
    conf->si_gear_ratio = buffer_get_float32_auto(buffer, &ind);
    conf->si_wheel_diameter = buffer_get_float32_auto(buffer, &ind);
    conf->si_battery_type = buffer[ind++];
    conf->si_battery_cells = buffer[ind++];
    conf->si_battery_ah = buffer_get_float32_auto(buffer, &ind);
    conf->si_motor_nl_current = buffer_get_float32_auto(buffer, &ind);
    conf->bms.type = buffer[ind++];
    conf->bms.limit_mode = buffer[ind++];
    conf->bms.t_limit_start = buffer_get_float16(buffer, 100, &ind);
    conf->bms.t_limit_end = buffer_get_float16(buffer, 100, &ind);
    conf->bms.soc_limit_start = buffer_get_float16(buffer, 1000, &ind);
    conf->bms.soc_limit_end = buffer_get_float16(buffer, 1000, &ind);
    conf->bms.fwd_can_mode = buffer[ind++];
    return true;
}

bool confgenerator_deserialize_appconf(const uint8_t *buffer, app_configuration *conf) {
	int32_t ind = 0;

	uint32_t signature = buffer_get_uint32(buffer, &ind);
	if (signature != APPCONF_SIGNATURE) {
		return false;
	}

	conf->controller_id = buffer[ind++];
	conf->timeout_msec = buffer_get_uint32(buffer, &ind);
	conf->timeout_brake_current = buffer_get_float32_auto(buffer, &ind);
	conf->can_status_rate_1 = buffer_get_uint16(buffer, &ind);
	conf->can_status_rate_2 = buffer_get_uint16(buffer, &ind);
	conf->can_status_msgs_r1 = buffer[ind++];
	conf->can_status_msgs_r2 = buffer[ind++];
	conf->can_baud_rate = buffer[ind++];
	conf->pairing_done = buffer[ind++];
	conf->permanent_uart_enabled = buffer[ind++];
	conf->shutdown_mode = buffer[ind++];
	conf->can_mode = buffer[ind++];
	conf->uavcan_esc_index = buffer[ind++];
	conf->uavcan_raw_mode = buffer[ind++];
	conf->uavcan_raw_rpm_max = buffer_get_float32_auto(buffer, &ind);
	conf->uavcan_status_current_mode = buffer[ind++];
	conf->servo_out_enable = buffer[ind++];
	conf->kill_sw_mode = buffer[ind++];
	conf->app_to_use = buffer[ind++];
	conf->app_ppm_conf.ctrl_type = buffer[ind++];
	conf->app_ppm_conf.pid_max_erpm = buffer_get_float32_auto(buffer, &ind);
	conf->app_ppm_conf.hyst = buffer_get_float32_auto(buffer, &ind);
	conf->app_ppm_conf.pulse_start = buffer_get_float32_auto(buffer, &ind);
	conf->app_ppm_conf.pulse_end = buffer_get_float32_auto(buffer, &ind);
	conf->app_ppm_conf.pulse_center = buffer_get_float32_auto(buffer, &ind);
	conf->app_ppm_conf.median_filter = buffer[ind++];
	conf->app_ppm_conf.safe_start = buffer[ind++];
	conf->app_ppm_conf.throttle_exp = buffer_get_float32_auto(buffer, &ind);
	conf->app_ppm_conf.throttle_exp_brake = buffer_get_float32_auto(buffer, &ind);
	conf->app_ppm_conf.throttle_exp_mode = buffer[ind++];
	conf->app_ppm_conf.ramp_time_pos = buffer_get_float32_auto(buffer, &ind);
	conf->app_ppm_conf.ramp_time_neg = buffer_get_float32_auto(buffer, &ind);
	conf->app_ppm_conf.multi_esc = buffer[ind++];
	conf->app_ppm_conf.tc = buffer[ind++];
	conf->app_ppm_conf.tc_max_diff = buffer_get_float32_auto(buffer, &ind);
	conf->app_ppm_conf.max_erpm_for_dir = buffer_get_float16(buffer, 1, &ind);
	conf->app_ppm_conf.smart_rev_max_duty = buffer_get_float32_auto(buffer, &ind);
	conf->app_ppm_conf.smart_rev_ramp_time = buffer_get_float32_auto(buffer, &ind);
	conf->app_adc_conf.ctrl_type = buffer[ind++];
	conf->app_adc_conf.hyst = buffer_get_float32_auto(buffer, &ind);
	conf->app_adc_conf.voltage_start = buffer_get_float16(buffer, 1000, &ind);
	conf->app_adc_conf.voltage_end = buffer_get_float16(buffer, 1000, &ind);
	conf->app_adc_conf.voltage_min = buffer_get_float16(buffer, 1000, &ind);
	conf->app_adc_conf.voltage_max = buffer_get_float16(buffer, 1000, &ind);
	conf->app_adc_conf.voltage_center = buffer_get_float16(buffer, 1000, &ind);
	conf->app_adc_conf.voltage2_start = buffer_get_float16(buffer, 1000, &ind);
	conf->app_adc_conf.voltage2_end = buffer_get_float16(buffer, 1000, &ind);
	conf->app_adc_conf.use_filter = buffer[ind++];
	conf->app_adc_conf.safe_start = buffer[ind++];
	conf->app_adc_conf.buttons = buffer[ind++];
	conf->app_adc_conf.voltage_inverted = buffer[ind++];
	conf->app_adc_conf.voltage2_inverted = buffer[ind++];
	conf->app_adc_conf.throttle_exp = buffer_get_float32_auto(buffer, &ind);
	conf->app_adc_conf.throttle_exp_brake = buffer_get_float32_auto(buffer, &ind);
	conf->app_adc_conf.throttle_exp_mode = buffer[ind++];
	conf->app_adc_conf.ramp_time_pos = buffer_get_float32_auto(buffer, &ind);
	conf->app_adc_conf.ramp_time_neg = buffer_get_float32_auto(buffer, &ind);
	conf->app_adc_conf.multi_esc = buffer[ind++];
	conf->app_adc_conf.tc = buffer[ind++];
	conf->app_adc_conf.tc_max_diff = buffer_get_float32_auto(buffer, &ind);
	conf->app_adc_conf.update_rate_hz = buffer_get_uint16(buffer, &ind);
	conf->app_uart_baudrate = buffer_get_uint32(buffer, &ind);
	conf->app_chuk_conf.ctrl_type = buffer[ind++];
	conf->app_chuk_conf.hyst = buffer_get_float32_auto(buffer, &ind);
	conf->app_chuk_conf.ramp_time_pos = buffer_get_float32_auto(buffer, &ind);
	conf->app_chuk_conf.ramp_time_neg = buffer_get_float32_auto(buffer, &ind);
	conf->app_chuk_conf.stick_erpm_per_s_in_cc = buffer_get_float32_auto(buffer, &ind);
	conf->app_chuk_conf.throttle_exp = buffer_get_float32_auto(buffer, &ind);
	conf->app_chuk_conf.throttle_exp_brake = buffer_get_float32_auto(buffer, &ind);
	conf->app_chuk_conf.throttle_exp_mode = buffer[ind++];
	conf->app_chuk_conf.multi_esc = buffer[ind++];
	conf->app_chuk_conf.tc = buffer[ind++];
	conf->app_chuk_conf.tc_max_diff = buffer_get_float32_auto(buffer, &ind);
	conf->app_chuk_conf.use_smart_rev = buffer[ind++];
	conf->app_chuk_conf.smart_rev_max_duty = buffer_get_float32_auto(buffer, &ind);
	conf->app_chuk_conf.smart_rev_ramp_time = buffer_get_float32_auto(buffer, &ind);
	conf->app_nrf_conf.speed = buffer[ind++];
	conf->app_nrf_conf.power = buffer[ind++];
	conf->app_nrf_conf.crc_type = buffer[ind++];
	conf->app_nrf_conf.retry_delay = buffer[ind++];
	conf->app_nrf_conf.retries = (int8_t)buffer[ind++];
	conf->app_nrf_conf.channel = (int8_t)buffer[ind++];
	conf->app_nrf_conf.address[0] = buffer[ind++];
	conf->app_nrf_conf.address[1] = buffer[ind++];
	conf->app_nrf_conf.address[2] = buffer[ind++];
	conf->app_nrf_conf.send_crc_ack = buffer[ind++];
	appconf6_skip_balance_placeholder(buffer, &ind);
	conf->app_pas_conf.ctrl_type = buffer[ind++];
	conf->app_pas_conf.sensor_type = buffer[ind++];
	conf->app_pas_conf.current_scaling = buffer_get_float16(buffer, 1000, &ind);
	conf->app_pas_conf.pedal_rpm_start = buffer_get_float16(buffer, 10, &ind);
	conf->app_pas_conf.pedal_rpm_end = buffer_get_float16(buffer, 10, &ind);
	conf->app_pas_conf.invert_pedal_direction = buffer[ind++];
	conf->app_pas_conf.magnets = buffer_get_uint16(buffer, &ind);
	conf->app_pas_conf.use_filter = buffer[ind++];
	conf->app_pas_conf.ramp_time_pos = buffer_get_float16(buffer, 100, &ind);
	conf->app_pas_conf.ramp_time_neg = buffer_get_float16(buffer, 100, &ind);
	conf->app_pas_conf.update_rate_hz = buffer_get_uint16(buffer, &ind);
	conf->imu_conf.type = buffer[ind++];
	conf->imu_conf.mode = buffer[ind++];
	conf->imu_conf.filter = buffer[ind++];
	conf->imu_conf.accel_lowpass_filter_x = buffer_get_float16(buffer, 1, &ind);
	conf->imu_conf.accel_lowpass_filter_y = buffer_get_float16(buffer, 1, &ind);
	conf->imu_conf.accel_lowpass_filter_z = buffer_get_float16(buffer, 1, &ind);
	conf->imu_conf.gyro_lowpass_filter = buffer_get_float16(buffer, 1, &ind);
	conf->imu_conf.sample_rate_hz = buffer_get_uint16(buffer, &ind);
	conf->imu_conf.use_magnetometer = buffer[ind++];
	conf->imu_conf.accel_confidence_decay = buffer_get_float32_auto(buffer, &ind);
	conf->imu_conf.mahony_kp = buffer_get_float32_auto(buffer, &ind);
	conf->imu_conf.mahony_ki = buffer_get_float32_auto(buffer, &ind);
	conf->imu_conf.madgwick_beta = buffer_get_float32_auto(buffer, &ind);
	conf->imu_conf.rot_roll = buffer_get_float32_auto(buffer, &ind);
	conf->imu_conf.rot_pitch = buffer_get_float32_auto(buffer, &ind);
	conf->imu_conf.rot_yaw = buffer_get_float32_auto(buffer, &ind);
	conf->imu_conf.accel_offsets[0] = buffer_get_float32_auto(buffer, &ind);
	conf->imu_conf.accel_offsets[1] = buffer_get_float32_auto(buffer, &ind);
	conf->imu_conf.accel_offsets[2] = buffer_get_float32_auto(buffer, &ind);
	conf->imu_conf.gyro_offsets[0] = buffer_get_float32_auto(buffer, &ind);
	conf->imu_conf.gyro_offsets[1] = buffer_get_float32_auto(buffer, &ind);
	conf->imu_conf.gyro_offsets[2] = buffer_get_float32_auto(buffer, &ind);

	return true;
}

